### ISSUE TITLE
Any appetite for a collab roadmap?

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/lingua-franca#46] opened 2019-11-13 17:54 UTC
Since there seems to be a lot of porting to do, I was thinking it might be good for devs and contributors to write up an authoritative list of what needs to be brought over or rewritten. I'd be happy to take some of it, but right now it feels a little like punching the air.

I haven't done it yet, because I'm in two of the wrong dev environments (=P) but I've considered just pulling Lingua Franca, doing a "replace all", and developing against the hundreds of ImportErrors that would result from that.

Alternatively, a flowchart, depicting existing parser/formatter functions (in core) as black boxes. I dunno. Something that'd make it easier to say, "I'll port this, you port that, somebody who speaks the language should just rewrite this one..."

**Comment by krisgesling** [comment] 2019-11-16 19:49
Hey Chance, I love that your thinking of this!

The good news is that Lingua Franca is the existing parser and formatter functions from core, and it hasn't diverged too much from there. We've tried to keep them in sync too, however I'm sure we haven't been 100% successful which is why we want to make the switch sooner rather than later.

@JarbasAl had offered to look at the merging of LF into core so will be good to hear if he's made any progress on it. Don't want to duplicate work if it's already been done.

**Comment by JarbasAl** [comment] 2020-11-02 23:13
essentially a duplicate of https://github.com/MycroftAI/lingua-franca/issues/114 now that core has migrated to lingua_franca

**Closed by JarbasAl** 2020-11-02 23:13 UTC
